# Generated by Django 5.0.2 on 2024-03-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_model',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job_model',
            name='number_of_openings',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
